# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248efeb2b73dacb5185715318dd89d3bf6f0b7775c09cb56c78456ea977d27ca4e42fc714e9a468d6775d986522ee2d34b7fdbb1799c6799709b55ab96979d1a

test:
  secret_key_base: ed9db894d95e2f91173d596874cbc55fff45403b92154ec33a3f64ccc6dc564d84a120ee37cb405941ac00c52f4927ad1659929091f5f82d8337faa0290225cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
